sudo: required
services:
  - docker

#Configuring docker-compose version
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

#Here we install docker-compose cli
before_install: 
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f docker-compose.test.yml build

script: 
  #Here you can define what scripts you want like running tests
  - docker-compose -f docker-compose.test.yml start --exit-code-from sut

after_success:
  #Here we will build the prod docker images and push them to dockerhub
  - docker build -t giurgibogdan/fazan:fazan-api .
  #Login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take the built images and push them to dockerhub
  - docker push giurgibogdan/fazan:fazan-api

