version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    restart: always
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    links:
      - mongo
    environment: 
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/fazan
    ports:
      - '3000:3001'
    