version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    restart: always
    volumes:
      - mongo_volume:/data/db
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    links:
      - mongo
    environment: 
      - PORT=9000
      - MONGODB_URI=mongodb://mongo:27017/fazan
    ports:
      - '9000:9000'
volumes:
  mongo_volume:
