version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    restart: always
    volumes:
      - mongo_volume:/data/db
    networks:
      - privateFazanNetwork
  nodejs:
    build: ./nodejs
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./nodejs:/app
    depends_on: 
      - mongo
    environment: 
      - PORT=9000
      - MONGODB_URI=mongodb://mongo:27017/fazan
    ports:
      - 9000:9000
    networks:
      - privateFazanNetwork
  nginx: 
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - nodejs
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - privateFazanNetwork
      - publicFazanNetwork

volumes:
  mongo_volume:

networks:
  privateFazanNetwork:
    internal: true
  publicFazanNetwork: